// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using admin_web_sell_phone.DataAccess;

#nullable disable

namespace admin_web_sell_phone.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("admin_web_sell_phone.Entity.tb_Chitiethoadon", b =>
                {
                    b.Property<int>("ID_HoaDon")
                        .HasColumnType("int");

                    b.Property<int>("ID_SanPham")
                        .HasColumnType("int");

                    b.Property<int>("Soluongmua")
                        .HasColumnType("int");

                    b.HasKey("ID_HoaDon", "ID_SanPham");

                    b.HasIndex("ID_SanPham");

                    b.ToTable("Chitiethoadon");
                });

            modelBuilder.Entity("admin_web_sell_phone.Entity.tb_Chitietphieunhap", b =>
                {
                    b.Property<int>("ID_PhieuNhap")
                        .HasColumnType("int");

                    b.Property<int>("ID_SanPham")
                        .HasColumnType("int");

                    b.Property<int>("Gianhap")
                        .HasColumnType("int");

                    b.Property<int>("Soluongnhap")
                        .HasColumnType("int");

                    b.HasKey("ID_PhieuNhap", "ID_SanPham");

                    b.HasIndex("ID_SanPham");

                    b.ToTable("Chitietphieunhap");
                });

            modelBuilder.Entity("admin_web_sell_phone.Entity.tb_Hoadon", b =>
                {
                    b.Property<int>("ID_Hoadon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Hoadon"));

                    b.Property<int>("ID_KhachHang")
                        .HasColumnType("int");

                    b.Property<int>("ID_NhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngaytaophieu")
                        .HasColumnType("datetime2");

                    b.Property<int>("TongDon")
                        .HasColumnType("int");

                    b.HasKey("ID_Hoadon");

                    b.HasIndex("ID_KhachHang");

                    b.HasIndex("ID_NhanVien");

                    b.ToTable("Hoadon");
                });

            modelBuilder.Entity("admin_web_sell_phone.Entity.tb_Khachhang", b =>
                {
                    b.Property<int>("ID_Khachhang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Khachhang"));

                    b.Property<string>("TenKhachhang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("sdt")
                        .HasColumnType("int");

                    b.HasKey("ID_Khachhang");

                    b.ToTable("Khachhang");
                });

            modelBuilder.Entity("admin_web_sell_phone.Entity.tb_Nhacungcap", b =>
                {
                    b.Property<int>("ID_Nhacungcap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Nhacungcap"));

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tennhacungcap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("sdt")
                        .HasColumnType("int");

                    b.HasKey("ID_Nhacungcap");

                    b.ToTable("Nhacungcap");
                });

            modelBuilder.Entity("admin_web_sell_phone.Entity.tb_Nhanvien", b =>
                {
                    b.Property<int>("ID_Nhanvien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Nhanvien"));

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hinhanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tennhanvien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sdt")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Nhanvien");

                    b.ToTable("Nhanvien");
                });

            modelBuilder.Entity("admin_web_sell_phone.Entity.tb_Phieunhap", b =>
                {
                    b.Property<int>("ID_Phieunhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Phieunhap"));

                    b.Property<int>("ID_NhaCungCap")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay_nhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tong_gia")
                        .HasColumnType("int");

                    b.HasKey("ID_Phieunhap");

                    b.HasIndex("ID_NhaCungCap");

                    b.ToTable("Phieunhap");
                });

            modelBuilder.Entity("admin_web_sell_phone.Entity.tb_Sanpham", b =>
                {
                    b.Property<int>("ID_sanpham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_sanpham"));

                    b.Property<string>("BaoHanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Camera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GiaBan")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_ThuongHieu")
                        .HasColumnType("int");

                    b.Property<string>("Kichthuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manhinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mausac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<string>("Ten_Dienthoai")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("ID_sanpham");

                    b.HasIndex("ID_ThuongHieu");

                    b.ToTable("Sanpham");
                });

            modelBuilder.Entity("admin_web_sell_phone.Entity.tb_Thuonghieu", b =>
                {
                    b.Property<int>("Id_Thuonghieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Thuonghieu"));

                    b.Property<string>("Tenthuonghieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Thuonghieu");

                    b.ToTable("Thuonghieu");
                });

            modelBuilder.Entity("admin_web_sell_phone.Entity.tb_Chitiethoadon", b =>
                {
                    b.HasOne("admin_web_sell_phone.Entity.tb_Hoadon", "tb_Hoadon")
                        .WithMany()
                        .HasForeignKey("ID_HoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("admin_web_sell_phone.Entity.tb_Sanpham", "tb_Sanpham")
                        .WithMany()
                        .HasForeignKey("ID_SanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tb_Hoadon");

                    b.Navigation("tb_Sanpham");
                });

            modelBuilder.Entity("admin_web_sell_phone.Entity.tb_Chitietphieunhap", b =>
                {
                    b.HasOne("admin_web_sell_phone.Entity.tb_Phieunhap", "tb_phieunhap")
                        .WithMany()
                        .HasForeignKey("ID_PhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("admin_web_sell_phone.Entity.tb_Sanpham", "tb_sanpham")
                        .WithMany()
                        .HasForeignKey("ID_SanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tb_phieunhap");

                    b.Navigation("tb_sanpham");
                });

            modelBuilder.Entity("admin_web_sell_phone.Entity.tb_Hoadon", b =>
                {
                    b.HasOne("admin_web_sell_phone.Entity.tb_Khachhang", "tb_Khachhang")
                        .WithMany()
                        .HasForeignKey("ID_KhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("admin_web_sell_phone.Entity.tb_Nhanvien", "tb_Nhanvien")
                        .WithMany()
                        .HasForeignKey("ID_NhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tb_Khachhang");

                    b.Navigation("tb_Nhanvien");
                });

            modelBuilder.Entity("admin_web_sell_phone.Entity.tb_Phieunhap", b =>
                {
                    b.HasOne("admin_web_sell_phone.Entity.tb_Nhacungcap", "tb_Nhacungcap")
                        .WithMany()
                        .HasForeignKey("ID_NhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tb_Nhacungcap");
                });

            modelBuilder.Entity("admin_web_sell_phone.Entity.tb_Sanpham", b =>
                {
                    b.HasOne("admin_web_sell_phone.Entity.tb_Thuonghieu", "tb_thuonghieu")
                        .WithMany()
                        .HasForeignKey("ID_ThuongHieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tb_thuonghieu");
                });
#pragma warning restore 612, 618
        }
    }
}
